"""initial_schema

Revision ID: 50c41b928159
Revises: 
Create Date: 2026-04-14 16:58:46.140074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c41b928159'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_id', sa.BigInteger(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('matches_won', sa.Integer(), nullable=False),
    sa.Column('matches_lost', sa.Integer(), nullable=False),
    sa.Column('matches_draw', sa.Integer(), nullable=False),
    sa.Column('tournaments_won', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('win_streak', sa.Integer(), nullable=False),
    sa.Column('best_win_streak', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('matches_today', sa.Integer(), nullable=False),
    sa.Column('last_match_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('manager1_id', sa.UUID(), nullable=False),
    sa.Column('manager2_id', sa.UUID(), nullable=True),
    sa.Column('team1_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('team2_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_turn', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_turns_main', sa.Integer(), nullable=False),
    sa.Column('total_turns_extra', sa.Integer(), nullable=False),
    sa.Column('used_players_main_m1', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('used_players_main_m2', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('used_players_extra_m1', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('used_players_extra_m2', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whistle_deck', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whistle_cards_drawn', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_manager1', sa.Integer(), nullable=False),
    sa.Column('score_manager2', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('loser_id', sa.UUID(), nullable=True),
    sa.Column('decided_by', sa.Text(), nullable=True),
    sa.Column('decided_by_lottery', sa.Boolean(), nullable=False),
    sa.Column('penalty_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('penalty_score_m1', sa.Integer(), nullable=False),
    sa.Column('penalty_score_m2', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_manager1_id'), 'matches', ['manager1_id'], unique=False)
    op.create_index(op.f('ix_matches_manager2_id'), 'matches', ['manager2_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('formation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_user_id'), 'teams', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_user_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_manager2_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_manager1_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
